[package]
name = "telepathy"
version = "1.0.0"
edition = "2021"

[dependencies]
argh = "0.1.10"

[dependencies.regioned]
git = "https://github.com/Rerumu/Regioned"
rev = "2099048"
features = ["dot"]

[build-dependencies]
cranelift-isle = "0.95.1"
